apiVersion: batch/v1
kind: Job
metadata:
  name: aioload-simple-producer-0
spec:
  template:
    metadata:
      labels:
        role: "producer"
        producerId: "0"
        experiment: "aioload-simple"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9092"
    spec:
      containers:
      - name: consumer
        image: lsstsqre/kafka-efd-demo:tickets-DM-16500
        imagePullPolicy: Always
        command:
          - "kafkaefd"
          - "aioload"
          - "produce"
          - "--name"
          - "aioload-simple"
          - "--count"
          - "8"
          - "--producer-count"
          - "1"
          - "--producer-id"
          - "0"
          - "--hertz"
          - "1"
      restartPolicy: Never
  backoffLimit: 4
