---
apiVersion: batch/v1
kind: Job
metadata:
  name: "create-influxdb-sink"
spec:
  template:
    metadata:
      labels:
        role: "create-influxdb-sink"
    spec:
      containers:
      - name: create-influxdb-sink
        image: lsstsqre/kafka-efd-demo:tickets-DM-17461
        imagePullPolicy: Always
        command:
          - "kafkaefd"
          - "admin"
          - "connectors"
          - "create"
          - "influxdb-sink"
          - "--database"
          - "kafkaefd"
          - "--upload"
          - "helloavro"
        env:
          - name: BROKER
            value: "confluent-cp-kafka-headless.kafka:9092"
          - name: SCHEMAREGISTRY
            value: "http://confluent-cp-schema-registry.kafka:8081"
          - name: KAFKA_CONNECT
            value: "http://confluent-cp-kafka-connect:8083"
      restartPolicy: Never
  backoffLimit: 4
