apiVersion: batch/v1
kind: Job
metadata:
  name: salmock-producer-telemetry
spec:
  template:
    metadata:
      labels:
        role: "producer"
        producerId: "2"
        experiment: "salmock"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9092"
    spec:
      containers:
      - name: consumer
        image: lsstsqre/kafka-efd-demo:tickets-DM-17052
        imagePullPolicy: Always
        command:
          - "kafkaefd"
          - "salmock"
          - "produce"
          - "--topic"
          - "ATAOS_timestamp"
          - "--topic"
          - "ATArchiver_sequencerHeartbeat"
          - "--topic"
          - "ATBuilding_loopTime"
          - "--topic"
          - "ATBuilding_timestamp"
          - "--topic"
          - "ATCalCS_loopTime"
          - "--topic"
          - "ATCalCS_timestamp"
          - "--topic"
          - "ATCamera_bonnShutter"
          - "--topic"
          - "ATCamera_heartbeat"
          - "--topic"
          - "ATCamera_wreb"
          - "--topic"
          - "ATCamera_wrebPower"
          - "--topic"
          - "ATDome_loopTime"
          - "--topic"
          - "ATDome_position"
          - "--topic"
          - "ATDome_timestamp"
          - "--topic"
          - "ATHexapod_positionStatus"
          - "--topic"
          - "ATMCS_measuredMotorVelocity"
          - "--topic"
          - "ATMCS_measuredTorque"
          - "--topic"
          - "ATMCS_mountEncoders"
          - "--topic"
          - "ATMCS_mountMotorEncoders"
          - "--topic"
          - "ATMCS_torqueDemand"
          - "--topic"
          - "ATMonochromator_loopTime"
          - "--topic"
          - "ATMonochromator_timestamp"
          - "--topic"
          - "ATPneumatics_loadCell"
          - "--topic"
          - "ATPneumatics_m1AirPressure"
          - "--topic"
          - "ATPneumatics_m2AirPressure"
          - "--topic"
          - "ATPneumatics_mainAirSourcePressure"
          - "--topic"
          - "ATSpectrograph_loopTime"
          - "--topic"
          - "ATSpectrograph_timestamp"
          - "--topic"
          - "ATTCS_loopTime"
          - "--topic"
          - "ATTCS_timestamp"
          - "--topic"
          - "ATThermoelectricCooler_fansSpeed"
          - "--topic"
          - "ATThermoelectricCooler_loopTime"
          - "--topic"
          - "ATThermoelectricCooler_processFlow"
          - "--topic"
          - "ATThermoelectricCooler_temperatureSensors"
          - "--topic"
          - "ATThermoelectricCooler_timestamp"
          - "--topic"
          - "ATThermoelectricCooler_unitUpTime"
          - "--topic"
          - "ATWhiteLight_loopTime"
          - "--topic"
          - "ATWhiteLight_timestamp"
          - "--topic"
          - "CBP_altitude"
          - "--topic"
          - "CBP_azimuth"
          - "--topic"
          - "CBP_focus"
          - "--topic"
          - "CBP_mask"
          - "--topic"
          - "CBP_parked"
          - "--topic"
          - "CBP_status"
          - "--topic"
          - "CatchupArchiver_sequencerHeartbeat"
          - "--topic"
          - "DIMM_loopTime"
          - "--topic"
          - "DIMM_status"
          - "--topic"
          - "DIMM_timestamp"
          - "--topic"
          - "DomeADB_status"
          - "--topic"
          - "DomeAPS_status"
          - "--topic"
          - "DomeLWS_status"
          - "--topic"
          - "DomeLouvers_status"
          - "--topic"
          - "DomeMONCS_status"
          - "--topic"
          - "DomeTHCS_status"
          - "--topic"
          - "Dome_summary"
          - "--topic"
          - "EAS_loopTime"
          - "--topic"
          - "EAS_timestamp"
          - "--topic"
          - "EFDTransformationServer_loopTime"
          - "--topic"
          - "EFDTransformationServer_timestamp"
          - "--topic"
          - "EFD_Summary"
          - "--topic"
          - "Environment_airPressure"
          - "--topic"
          - "Environment_airTemperature"
          - "--topic"
          - "Environment_dewPoint"
          - "--topic"
          - "Environment_precipitation"
          - "--topic"
          - "Environment_relativeHumidity"
          - "--topic"
          - "Environment_snowDepth"
          - "--topic"
          - "Environment_soilTemperature"
          - "--topic"
          - "Environment_solarNetRadiation"
          - "--topic"
          - "Environment_weather"
          - "--topic"
          - "Environment_windDirection"
          - "--topic"
          - "Environment_windGustDirection"
          - "--topic"
          - "Environment_windSpeed"
          - "--topic"
          - "FiberSpectrograph_loopTime_ms"
          - "--topic"
          - "FiberSpectrograph_spectTemperature"
          - "--topic"
          - "FiberSpectrograph_timestamp"
          - "--topic"
          - "HVAC_lowerAHUStatus"
          - "--topic"
          - "HVAC_lowerChillerStatus"
          - "--topic"
          - "HVAC_whiteRoomAHU"
          - "--topic"
          - "Hexapod_Actuators"
          - "--topic"
          - "Hexapod_Application"
          - "--topic"
          - "Hexapod_Electrical"
          - "--topic"
          - "IOTA_loopTime"
          - "--topic"
          - "IOTA_timestamp"
          - "--topic"
          - "LinearStage_position"
          - "--topic"
          - "MTArchiver_sequencerHeartbeat"
          - "--topic"
          - "MTCalCS_loopTime"
          - "--topic"
          - "MTCalCS_timestamp"
          - "--topic"
          - "MTCamera_ccs"
          - "--topic"
          - "MTCamera_clusterEncoder"
          - "--topic"
          - "MTCamera_cold"
          - "--topic"
          - "MTCamera_cyro"
          - "--topic"
          - "MTCamera_filter"
          - "--topic"
          - "MTCamera_gas"
          - "--topic"
          - "MTCamera_gds"
          - "--topic"
          - "MTCamera_heartbeat"
          - "--topic"
          - "MTCamera_pcms"
          - "--topic"
          - "MTCamera_prot"
          - "--topic"
          - "MTCamera_purge"
          - "--topic"
          - "MTCamera_sas"
          - "--topic"
          - "MTCamera_sds"
          - "--topic"
          - "MTCamera_shutter"
          - "--topic"
          - "MTCamera_was"
          - "--topic"
          - "MTCamera_wds"
          - "--topic"
          - "MTDomeTrajectory_loopTime"
          - "--topic"
          - "MTDomeTrajectory_timestamp"
          - "--topic"
          - "MTGuider_loopTime"
          - "--topic"
          - "MTGuider_timestamp"
          - "--topic"
          - "MTLaserTracker_loopTime"
          - "--topic"
          - "MTLaserTracker_timestamp"
          - "--topic"
          - "MTM1M3TS_thermalData"
          - "--topic"
          - "MTM1M3_accelerometerData"
          - "--topic"
          - "MTM1M3_forceActuatorData"
          - "--topic"
          - "MTM1M3_forceActuatorPressure"
          - "--topic"
          - "MTM1M3_gyroData"
          - "--topic"
          - "MTM1M3_hardpointActuatorData"
          - "--topic"
          - "MTM1M3_hardpointMonitorData"
          - "--topic"
          - "MTM1M3_imsData"
          - "--topic"
          - "MTM1M3_inclinometerData"
          - "--topic"
          - "MTM1M3_outerLoopData"
          - "--topic"
          - "MTM1M3_pidData"
          - "--topic"
          - "MTM1M3_powerData"
          - "--topic"
          - "MTM2_actuatorLimitSwitches"
          - "--topic"
          - "MTM2_axialActuatorAbsolutePositionSteps"
          - "--topic"
          - "MTM2_axialActuatorPositionAbsoluteEncoderPositionMeasured"
          - "--topic"
          - "MTM2_axialForcesMeasured"
          - "--topic"
          - "MTM2_mirrorPositionMeasured"
          - "--topic"
          - "MTM2_powerStatus"
          - "--topic"
          - "MTM2_rawDisplacement"
          - "--topic"
          - "MTM2_rawTelemetry"
          - "--topic"
          - "MTM2_stepVectorUpdate"
          - "--topic"
          - "MTM2_systemStatus"
          - "--topic"
          - "MTM2_tangentActuatorAbsolutePositionSteps"
          - "--topic"
          - "MTM2_tangentActuatorPositionAbsoluteEncoderPositionMeasured"
          - "--topic"
          - "MTM2_tangentForcesMeasured"
          - "--topic"
          - "MTM2_targetForces"
          - "--topic"
          - "MTM2_temperaturesMeasured"
          - "--topic"
          - "MTM2_zenithAngleMeasured"
          - "--topic"
          - "MTMount_Auxiliary_Boxes"
          - "--topic"
          - "MTMount_Auxliary_Cabinet_Azimuth"
          - "--topic"
          - "MTMount_Azimuth"
          - "--topic"
          - "MTMount_Azimuth_Cable_Wrap"
          - "--topic"
          - "MTMount_Azimuth_Drives"
          - "--topic"
          - "MTMount_Azimuth_Drives_Thermal"
          - "--topic"
          - "MTMount_Balancing"
          - "--topic"
          - "MTMount_Balancing_Drives"
          - "--topic"
          - "MTMount_Camera_Cable_Wrap"
          - "--topic"
          - "MTMount_Compressed_Air"
          - "--topic"
          - "MTMount_Cooling"
          - "--topic"
          - "MTMount_Deployable_Platforms"
          - "--topic"
          - "MTMount_Dynalene_Cooling"
          - "--topic"
          - "MTMount_Elevation"
          - "--topic"
          - "MTMount_Elevation_Drives"
          - "--topic"
          - "MTMount_Elevation_Drives_Thermal"
          - "--topic"
          - "MTMount_Encoder_EIB"
          - "--topic"
          - "MTMount_General"
          - "--topic"
          - "MTMount_General_Purpose_Glycol_Water"
          - "--topic"
          - "MTMount_Locking_Pins"
          - "--topic"
          - "MTMount_Main_Power_Supply"
          - "--topic"
          - "MTMount_Main_Power_Supply_Cabinet"
          - "--topic"
          - "MTMount_Mirror_Cover"
          - "--topic"
          - "MTMount_Mirror_Cover_Locks"
          - "--topic"
          - "MTMount_Mount_Control_Main_Cabinet"
          - "--topic"
          - "MTMount_OSS"
          - "--topic"
          - "MTMount_Safety_System"
          - "--topic"
          - "MTMount_Top_End_Chiller"
          - "--topic"
          - "MTOFC_loopTimeMs"
          - "--topic"
          - "MTOFC_timestamp"
          - "--topic"
          - "MTTCS_aOCS"
          - "--topic"
          - "MTTCS_kernelDawdleFilter"
          - "--topic"
          - "MTTCS_kernelFK5Target"
          - "--topic"
          - "MTTCS_kernelOpticsVt"
          - "--topic"
          - "MTTCS_kernelPointingControl"
          - "--topic"
          - "MTTCS_kernelPointingLog"
          - "--topic"
          - "MTTCS_kernelPointingModel"
          - "--topic"
          - "MTTCS_kernelSite"
          - "--topic"
          - "MTTCS_kernelTarget"
          - "--topic"
          - "MTTCS_kernelTimeKeeper"
          - "--topic"
          - "MTTCS_kernelTrackRefSys"
          - "--topic"
          - "MTTCS_kernelTrackingTarget"
          - "--topic"
          - "MTTCS_loopTime"
          - "--topic"
          - "MTTCS_timestamp"
          - "--topic"
          - "MTTCS_zEMAX"
          - "--topic"
          - "MTVMS_M1M3"
          - "--topic"
          - "MTVMS_M2"
          - "--topic"
          - "MTVMS_TMA"
          - "--topic"
          - "MTVMS_cameraRotator"
          - "--topic"
          - "MTWEP_loopTimeMs"
          - "--topic"
          - "MTWEP_timestamp"
          - "--topic"
          - "OCS_sequencerHeartbeat"
          - "--topic"
          - "PointingComponent_currentTargetStatus"
          - "--topic"
          - "PointingComponent_currentTimesToLimits"
          - "--topic"
          - "PointingComponent_guidingAndOffsets"
          - "--topic"
          - "PointingComponent_mountStatus"
          - "--topic"
          - "PointingComponent_nextTargetStatus"
          - "--topic"
          - "PointingComponent_nextTimesToLimits"
          - "--topic"
          - "PointingComponent_prospectiveTargetStatus"
          - "--topic"
          - "PointingComponent_prospectiveTimesToLimits"
          - "--topic"
          - "PointingComponent_timeAndDate"
          - "--topic"
          - "PromptProcessing_sequencerHeartbeat"
          - "--topic"
          - "Rotator_Application"
          - "--topic"
          - "Rotator_Electrical"
          - "--topic"
          - "Rotator_Motors"
          - "--topic"
          - "Scheduler_avoidanceRegions"
          - "--topic"
          - "Scheduler_bulkCloud"
          - "--topic"
          - "Scheduler_cameraConfig"
          - "--topic"
          - "Scheduler_cloudMap"
          - "--topic"
          - "Scheduler_domeConfig"
          - "--topic"
          - "Scheduler_downtime"
          - "--topic"
          - "Scheduler_driverConfig"
          - "--topic"
          - "Scheduler_generalPropConfig"
          - "--topic"
          - "Scheduler_interestedProposal"
          - "--topic"
          - "Scheduler_loopTimeMs"
          - "--topic"
          - "Scheduler_nightSummary"
          - "--topic"
          - "Scheduler_obsSiteConfig"
          - "--topic"
          - "Scheduler_observation"
          - "--topic"
          - "Scheduler_observatoryState"
          - "--topic"
          - "Scheduler_opticsLoopCorrConfig"
          - "--topic"
          - "Scheduler_parkConfig"
          - "--topic"
          - "Scheduler_photometricQuality"
          - "--topic"
          - "Scheduler_predictedSchedule"
          - "--topic"
          - "Scheduler_rotatorConfig"
          - "--topic"
          - "Scheduler_schedulerConfig"
          - "--topic"
          - "Scheduler_seeing"
          - "--topic"
          - "Scheduler_sequencePropConfig"
          - "--topic"
          - "Scheduler_skyBrightness"
          - "--topic"
          - "Scheduler_slewConfig"
          - "--topic"
          - "Scheduler_surveyTopology"
          - "--topic"
          - "Scheduler_telescopeConfig"
          - "--topic"
          - "Scheduler_temperature"
          - "--topic"
          - "Scheduler_timeHandler"
          - "--topic"
          - "Scheduler_timestamp"
          - "--topic"
          - "Scheduler_wind"
          - "--topic"
          - "Sequencer_sequencerHeartbeat"
          - "--topic"
          - "SummitFacility_loopTime"
          - "--topic"
          - "SummitFacility_timestamp"
          - "--topic"
          - "TunableLaser_temperature"
          - "--topic"
          - "TunableLaser_wavelength"
          - "--period"
          - "0.01"
          - "--log-level"
          - "info"
      restartPolicy: Never
  backoffLimit: 4
