---
apiVersion: v1
kind: ConfigMap
metadata:
  name: saltransform
data:
  BROKER: "confluent-cp-kafka-headless.kafka:9092"
  SCHEMAREGISTRY: "http://confluent-cp-schema-registry.kafka:8081"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "saltransform-mtm1m3ts"
spec:
  template:
    metadata:
      labels:
        role: "saltransformer"
        subsystem: "MTM1M3TS"
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/port: "9092"
    spec:
      containers:
      - name: saltransformer
        image: lsstsqre/kafka-efd-demo:tickets-DM-17282
        imagePullPolicy: Always
        command:
          - "kafkaefd"
          - "saltransform"
          - "init"
          - "--subsystem"
          - "MTM1M3TS"
        envFrom:
        - configMapRef:
            name: saltransform
      restartPolicy: Never
  backoffLimit: 4
